### PR TITLE
Updated Code from ActionSheetPicker

### PR DESCRIPTION
**Pull request by jononon**
Updated the `ActionSheetDatePicker`, `AbstractActionSheetPicker`, and `ActionSheetStringPicker` to match http://github.com/TimCinel/ActionSheetPicker.

### CODE REVIEW

**Comment by jmfieldman** [comment]
Should this still be merged?

**Comment by jononon** [comment]
Only if you want to update  `ActionSheetDatePicker`, `AbstractActionSheetPicker`, and `ActionSheetStringPicker` to match http://github.com/TimCinel/ActionSheetPicker. Otherwise I'd say no. If it ain't broke...

**Comment by jburns20** [comment]
Well on iOS 8 it *is* broke...

**Comment by jmfieldman** [comment]
so is that a yes or no?  i just don't want to merge something that will break stuff going forward

**Comment by jononon** [comment]
No, don't merge it. Its not needed.

**Pull request closed without merging**
